version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: real_estate
      MYSQL_USER: shinkg
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  nextjs:
    container_name: realestate_app_container
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://shinkg:password@mysql:3306/real_estate
    depends_on:
      - mysql

volumes:
  mysql-data:
