version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  graphql:
    build: ./backend
    container_name: graphql
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@mysql:3306/${DB_NAME}
    ports:
      - "4000:4000"
    networks:
      - app-network

  nextjs:
    build: ./frontend
    container_name: nextjs
    depends_on:
      - graphql
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
