version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: real_estate
      MYSQL_USER: root
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  graphql:
    build: ./backend
    container_name: graphql
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:P@ssw0rd@mysql:3306/real_estate
    ports:
      - "4000:4000"

  nextjs:
    build: ./frontend
    container_name: nextjs
    depends_on:
      - graphql
    ports:
      - "3000:3000"

volumes:
  mysql-data: