version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: realestate
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  nextjs:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:password@db:3306/realestate
    depends_on:
      - db

volumes:
  mysql-data:
